version: '2.2'

services:
  fakesmtp:
    image: gessnerfl/fake-smtp-server:1.10.4
    container_name: fakesmtp
    hostname: fakesmtp
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8025:8025"
