name: Snyk
on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: 0 8,16 * * *

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11

      - name: Snyk Monitor execution
        run: snyk test --project-name=gessnerfl/fake-smtp-server
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

